<a href="https://colab.research.google.com/github/tharuni777/kalahasthi-tharu/blob/master/Classification_red_wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
dataset = pd.read_csv('/content/winequality-red.csv')

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [12]:
X = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.20)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc = StandardScaler()

In [17]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [19]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [20]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [21]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [24]:
l_c

array([[ 0,  1,  0,  0,  0,  0],
       [ 0,  0,  4,  4,  0,  0],
       [ 0,  1, 96, 27,  1,  0],
       [ 0,  0, 52, 71,  7,  0],
       [ 0,  0,  4, 29, 15,  0],
       [ 0,  0,  0,  5,  3,  0]])

In [25]:
k_c

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  0,  3,  5,  0,  0],
       [ 1,  3, 78, 42,  0,  1],
       [ 0,  1, 52, 70,  7,  0],
       [ 0,  1,  8, 20, 19,  0],
       [ 0,  0,  0,  4,  4,  0]])

In [26]:
d_c

array([[ 0,  1,  0,  0,  0,  0],
       [ 1,  1,  2,  4,  0,  0],
       [ 0,  5, 92, 26,  2,  0],
       [ 0,  5, 27, 87, 10,  1],
       [ 0,  0,  8, 14, 24,  2],
       [ 0,  0,  0,  6,  2,  0]])

In [27]:
r_c

array([[  0,   0,   1,   0,   0,   0],
       [  1,   0,   4,   3,   0,   0],
       [  0,   0, 101,  23,   1,   0],
       [  0,   0,  36,  86,   8,   0],
       [  0,   0,   1,  24,  22,   1],
       [  0,   0,   0,   5,   3,   0]])

In [28]:
s_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   5,   3,   0,   0],
       [  0,   0, 100,  25,   0,   0],
       [  0,   0,  56,  74,   0,   0],
       [  0,   0,   4,  44,   0,   0],
       [  0,   0,   0,   8,   0,   0]])

In [29]:
ks_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   3,   5,   0,   0],
       [  0,   0, 100,  25,   0,   0],
       [  0,   0,  48,  77,   5,   0],
       [  0,   0,   5,  27,  16,   0],
       [  0,   0,   0,   6,   2,   0]])

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [32]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.56875
KNN: 0.521875
Decision Tree: 0.6375
Random Forest: 0.653125
Linear SVC: 0.54375
Kernel SVC: 0.56875


conslusion : since ramdom forest accuricy is high we r considering this
thank you
kalahasthi tharuni
